language: rust
version: ~> 1.0
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
    - os: osx
  fast_finish: true
os:
  - linux
  - osx
dist: focal
cache: cargo
script:
  - make run && make run-dev