[package]
name = "cocom"
version = "1.2.0"
authors = ["LamdaLamdaLamda"]
edition = "2018"
description = "NTP-Client purely written in Rust."
license = "GPL-3.0-only"
repository = "https://github.com/LamdaLamdaLamda/cocom"
readme = "README.md"

[dependencies]
byteorder = "0.5"
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
libc = "0.2"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = "z"
overflow-checks = false
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true