name: Cocom build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
<<<<<<< HEAD

=======
    
>>>>>>> 67a02277e2fd25090201cf2acfd5a0ee620b5788
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: run-dev
        run: make run && make run-dev
