name: macOS

on:
  push:
  pull_request:

jobs:
  test:
    name: Build & test

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - uses: extractions/setup-just@v2

      - name: Build (debug)
        run: just build-dev

      - name: Build (release)
        run: just build

      - name: Run test suite
        run: just test

      - name: Smoke-test debug binary
        run: just run-dev

      - name: Smoke-test release binary
        run: just run
